version: '3.4'

services:
  pocketmoodle:
    image: dakexduck/pocket-moodle:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment: 
      TOKEN: "${TOKEN}"
      TOKEN_notify: "${TOKEN_notify}"
      COOKIE_KEY: "${COOKIE_KEY}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_DB: "${REDIS_DB}"
      REDIS_USER: "${REDIS_USER}"
      REDIS_PASSWD: "${REDIS_PASSWD}"
      ROBO_LOGIN: "${ROBO_LOGIN}"
      ROBO_PASSWD_1: "${ROBO_PASSWD_1}"
      ROBO_PASSWD_2: "${ROBO_PASSWD_2}"
    ports:
      - 8080:8080
