name: Code Checks

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pylint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11.7
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.7
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.dev.txt

      - name: Run pylint
        run: |
          pylint $(git ls-files '*.py')

  mypy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11.7
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.7
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.dev.txt

      - name: Run mypy
        run: |
          mypy .

  black:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11.7
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.7
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.dev.txt

      - name: Run black
        run: |
          black --diff --check .

  isort:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11.7
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.7
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.dev.txt
          pip install isort

      - name: Run isort
        run: |
          isort --diff --check-only .
