name: Code Checks

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  code-checks:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.dev.txt

      - name: Run isort
        run: isort --diff --check-only .
      
      - name: Run black
        run: black --diff --check .

      - name: Run pylint
        run: pylint --recursive=y .

      - name: Run mypy
        run: mypy .
