name: Code Checks

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  setup-and-check:
    runs-on: self-hosted
    strategy:
      matrix:
        tool: [pylint, mypy, black, isort]

    steps:
      - name: Go to pocket-moodle
        run: cd /home/aitusa/pocket-moodle

      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint mypy black isort

      - name: Run Tool
        run: |
          if [ "${{ matrix.tool }}" = "pylint" ]; then
            pylint $(git ls-files '*.py')
          elif [ "${{ matrix.tool }}" = "mypy" ]; then
            mypy .
          elif [ "${{ matrix.tool }}" = "black" ]; then
            black --diff --check .
          elif [ "${{ matrix.tool }}" = "isort" ]; then
            isort --diff --check-only .
          fi
