name: Checks

on:
  push:
    branches:
      - main
      - test
      - dev
  pull_request:
    branches:
      - main
      - test
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pylint:
    runs-on: ubuntu-22.04
    steps:
    - name: Set up Python3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint black mypy isort
    
    - name: Run pylint
      run: |
        pylint **/*.py
      
    - name: Run mypy
      run: |
        mypy **/*.py
      
    - name: Run black
      run: |
        black --check .
      
    - name: Run isort
      run: |
        isort --check-only .
